# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
default_install_hook_types: [pre-push, pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents] # for .clang-format
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: ''
    hooks:
      - id: isort